## HW4_ Pandas excercise

In [1]:
import pandas as pd

In [8]:
score = {'학번': [201621445,201621447,201621452, 201621435, 201621433],
       '이름':['채정우','안상호','고한솔', '박태현', '원도형'],
       '학과':['e-비즈니스학과','ICT-융합학과','A.I 융합학과 탈락','e-비즈니스학과','서강대학교'],
       'Quiz':[15,20,20,17,18],
       '중간고사':[10,20,15,18,16]}
df = pd.DataFrame(score)
df

학번   이름           학과  Quiz  중간고사
0  201621445  채정우     e-비즈니스학과    15    10
1  201621447  안상호     ICT-융합학과    20    20
2  201621452  고한솔  A.I 융합학과 탈락    20    15
3  201621435  박태현     e-비즈니스학과    17    18
4  201621433  원도형        서강대학교    18    16

In [9]:
df['학번']

0    201621445
1    201621447
2    201621452
3    201621435
4    201621433
Name: 학번, dtype: int64

In [10]:
df[["이름","중간고사"]]

이름  중간고사
0  채정우    10
1  안상호    20
2  고한솔    15
3  박태현    18
4  원도형    16

In [11]:
df = df.reindex([2, 0, 4, 1, 3])
df

학번   이름           학과  Quiz  중간고사
2  201621452  고한솔  A.I 융합학과 탈락    20    15
0  201621445  채정우     e-비즈니스학과    15    10
4  201621433  원도형        서강대학교    18    16
1  201621447  안상호     ICT-융합학과    20    20
3  201621435  박태현     e-비즈니스학과    17    18

In [12]:
print(df.iloc[3])
print(df.loc[1])

학번      201621447
이름            안상호
학과       ICT-융합학과
Quiz           20
중간고사           20
Name: 1, dtype: object
학번      201621447
이름            안상호
학과       ICT-융합학과
Quiz           20
중간고사           20
Name: 1, dtype: object


In [13]:
print(df.iloc[:, [1, 4]])
print(df.loc[:, ['이름', '중간고사']])

    이름  중간고사
2  고한솔    15
0  채정우    10
4  원도형    16
1  안상호    20
3  박태현    18
    이름  중간고사
2  고한솔    15
0  채정우    10
4  원도형    16
1  안상호    20
3  박태현    18


In [14]:
df['중간고사'].mean()

15.8

In [15]:
df['중간고사'].idxmin()

0

In [17]:
df.loc[df['Quiz'].idxmax()]['학번']

201621452

In [21]:
df.loc[df['Quiz'].idxmax(), '학번'] # 안에 넣어서도 가능 

201621452

In [22]:
df.describe() # 기초 통계량 뽑기 

학번      Quiz       중간고사
count  5.000000e+00   5.00000   5.000000
mean   2.016214e+08  18.00000  15.800000
std    8.111720e+00   2.12132   3.768289
min    2.016214e+08  15.00000  10.000000
25%    2.016214e+08  17.00000  15.000000
50%    2.016214e+08  18.00000  16.000000
75%    2.016214e+08  20.00000  18.000000
max    2.016215e+08  20.00000  20.000000

In [25]:
quiz_mean = df['Quiz'].mean()
df[df['Quiz'] > quiz_mean]['이름'] # 평균 이상인 학생들 이름 출력 

2    고한솔
1    안상호
Name: 이름, dtype: object

In [26]:
quiz_mean = df['Quiz'].mean()
mid_mean = df['중간고사'].mean()
df[(df['Quiz'] > quiz_mean) & (df['중간고사'] > mid_mean)] # 퀴즈 중간고사 점수 모두 평균 이상인 학생들 record 

학번   이름        학과  Quiz  중간고사
1  201621447  안상호  ICT-융합학과    20    20

In [27]:
df['학과'].value_counts() # 학과 별 학생 수 

e-비즈니스학과       2
A.I 융합학과 탈락    1
서강대학교          1
ICT-융합학과       1
Name: 학과, dtype: int64

In [29]:
df.groupby('학과')['중간고사'].mean() # groupby 그룹별로 묶어줘서 값 구하기 가능 

학과
A.I 융합학과 탈락    15
ICT-융합학과       20
e-비즈니스학과       14
서강대학교          16
Name: 중간고사, dtype: int64

In [30]:
df.mean()

학번      201621442.4
Quiz           18.0
중간고사           15.8
dtype: float64

In [31]:
list(df.groupby('학과')) # 학과 별로 묶어주기 

[('A.I 융합학과 탈락',           학번   이름           학과  Quiz  중간고사
  2  201621452  고한솔  A.I 융합학과 탈락    20    15),
 ('ICT-융합학과',           학번   이름        학과  Quiz  중간고사
  1  201621447  안상호  ICT-융합학과    20    20),
 ('e-비즈니스학과',           학번   이름        학과  Quiz  중간고사
  0  201621445  채정우  e-비즈니스학과    15    10
  3  201621435  박태현  e-비즈니스학과    17    18),
 ('서강대학교',           학번   이름     학과  Quiz  중간고사
  4  201621433  원도형  서강대학교    18    16)]

### HW4_ Numpy Exercise

In [33]:
import numpy as np

In [34]:
a = np.zeros((3, 4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [54]:
for i in range(a.shape[0]):
    for j in range(a.shape[1]):
        a[i, j] = i * 4 + j + 1
a

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

In [55]:
num = 1
for i in range(a.shape[0]):
    for j in range(a.shape[1]):
        a[i, j] =  num
        num += 1 # a += b -> a = a+b 
a

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

In [56]:
a[1, 2]

7.0

In [57]:
a.shape

(3, 4)

In [58]:
a[[1], :] # 둘째행 꺼내 인덱싱 

array([[5., 6., 7., 8.]])

In [59]:
a[:,[0, 2]] # 둘째 셋째 열 나오게 

array([[ 1.,  3.],
       [ 5.,  7.],
       [ 9., 11.]])

In [60]:
result = np.asarray([a[i, j] for i in range(a.shape[0]) for  j in range(a.shape[1]) if a[i, j] <= 6])
result 


array([1., 2., 3., 4., 5., 6.])

In [61]:
a[a <= 6] # a에서 6보다 작거나 같은 값들 나오게 불리안 인덱싱 

array([1., 2., 3., 4., 5., 6.])

In [62]:
b = np.random.random((3, 4))
b # 무작위 행렬 생성 

array([[0.10783731, 0.98409541, 0.2898417 , 0.39039657],
       [0.28117249, 0.84472491, 0.27739703, 0.40848952],
       [0.0661703 , 0.36580262, 0.09008762, 0.95845296]])

In [63]:
c = a * b
c

array([[ 0.10783731,  1.96819082,  0.86952511,  1.56158628],
       [ 1.40586243,  5.06834944,  1.94177919,  3.26791616],
       [ 0.59553267,  3.65802622,  0.99096385, 11.50143552]])

In [69]:
a *= b # 할당 연산자 연습 
a

array([[ 0.10783731,  1.96819082,  0.86952511,  1.56158628],
       [ 1.40586243,  5.06834944,  1.94177919,  3.26791616],
       [ 0.59553267,  3.65802622,  0.99096385, 11.50143552]])

In [64]:
d = b.T # 전치행렬 만들기 
d

array([[0.10783731, 0.28117249, 0.0661703 ],
       [0.98409541, 0.84472491, 0.36580262],
       [0.2898417 , 0.27739703, 0.09008762],
       [0.39039657, 0.40848952, 0.95845296]])

In [65]:
d.shape

(4, 3)

In [66]:
print(a.shape, d.shape)

(3, 4) (4, 3)


In [67]:
e = a.dot(d)
e # 행렬 곱도 가능 

array([[ 4.50713952,  4.43677146,  4.90185025],
       [11.59582349, 11.68390721, 10.82390425],
       [18.68450746, 18.93104297, 16.74595825]])

In [68]:
np.sum(e, axis=1) # 각혈의 합 계산 e에 대해서 

array([13.84576122, 34.10363495, 54.36150868])